# (KO) 이 파일은 Cloudflare Pages 및 Functions 배포를 위한 설정 파일입니다.
# (EN) This is the configuration file for Cloudflare Pages and Functions deployment.

name = "candlespinner-functions"
compatibility_date = "2025-10-08"

# (KO) Cloudflare Functions가 Node.js API(예: 'crypto')와 호환되도록 합니다.
# (EN) Ensures that Cloudflare Functions are compatible with Node.js APIs (e.g., 'crypto').
compatibility_flags = ["nodejs_compat"]

# (KO) Vite의 빌드 출력 디렉토리를 지정합니다.
# (EN) Specifies the build output directory for Vite.
pages_build_output_dir = "dist"

# (KO) Commit-Reveal 스킴을 위해 사용할 KV 네임스페이스를 정의합니다.
# (EN) Defines the KV namespace to be used for the Commit-Reveal scheme.
[[kv_namespaces]]
binding = "SPIN_COMMITMENTS"
id = "101174f2d41740f3a2f64374d95fc347" # (KO) 사용자로부터 제공받은 프로덕션 ID로 업데이트되었습니다. (EN) Updated with the production ID provided by the user.
preview_id = "preview_namespace_for_commitments" # (KO) `wrangler dev`를 위한 미리보기 ID입니다. (EN) This is the preview ID for `wrangler dev`.