name = "tonslotmachin"
compatibility_date = "2025-10-03"

main = "src/index.js"

# [추가] 이제 workers.dev 주소 대신, 우리의 커스텀 도메인을 사용하도록 설정합니다.
[[routes]]
pattern = "aiandyou.me/*"
custom_domain = true

[site]
bucket = "./public"
