name = "tonslotmachin" # 스크린샷에 보이는 이름으로 수정했습니다.
compatibility_date = "2025-10-03" # [수정] 미래 날짜가 아닌, 실제 빌드 날짜로 변경했습니다.

# 워커의 '두뇌'인 시작 스크립트 파일을 지정합니다.
main = "src/index.js"

workers_dev = true

# 웹사이트의 '얼굴'인 정적 파일들이 담긴 폴더를 지정합니다.
[site]
bucket = "./public"
