name = "candlespinner-backend"
main = "functions/spin.js" # 기본 진입점, 실제로는 각 함수 파일이 엔드포인트가 됨
compatibility_date = "2024-05-01"

# Node.js와의 호환성을 위한 필수 플래그
# This flag is essential for Node.js compatibility
compatibility_flags = ["nodejs_compat"]

# [dev]
# port = 8788
# local_protocol = "http"