name = "tonslotmachin"
compatibility_date = "2025-10-03"

# 워커의 '두뇌'인 시작 스크립트 파일을 지정합니다.
main = "src/index.js"

# 웹사이트의 '얼굴'인 정적 파일들이 담긴 폴더를 지정합니다.
[site]
bucket = "./public"

# workers.dev 주소를 사용하도록 명시합니다.
workers_dev = true
